### PR TITLE
Stop Visual Studio from quitting when project contains <PackageReference>

### LINKED ISSUE #9: Visual Studio quits when changing branches
### Installed product versions
- Visual Studio: 2017
- This extension: 1.1.16

## What happened

Visual Studio exited when checking out a branch. This happened again when returning to the original branch.

**Steps to Reproduce**

1. Check out https://github.com/github/VisualStudio/pull/2060/commits/eed1e4e211143de5cb52f5ae0df20e002764ff1e
2.  Check out https://github.com/github/visualstudio/tree/refactor/package-reference

**Expected behavior:**

The target PR branch is checked out.

**Actual behavior:**

Visual Studio quits and restarts.

**Log file:**

I found the two identical exceptions in the Windows `Event Viewer`. This will be from changing branches in both directions.

image

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at EnvDTE.ProjectItem.get_FileNames(Int16)
   at StringResourceVisualizer.VSPackage+<HandleOpenSolution>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

```
Faulting application name: devenv.exe, version: 15.8.28010.2046, time stamp: 0x5bb6cee9
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0xade8d4fe
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x58d8
Faulting application start time: 0x01d47dcff03b95df
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8e9ddd47-7bb7-4d0f-a2a7-0e36f571d63e
Faulting package full name: 
Faulting package-relative application ID: 
```

### Related

- https://github.com/github/VisualStudio/issues/2061

### PR DESCRIPTION
**Pull request by jcansdale**
### What this PR does

Fixes #9

- Catch any exceptions thrown by `HandleOpenSolution` and `FileAndForget`
- Get file path `ProjectItem.FileNames[1]` because it's a 1 based array [see](https://docs.microsoft.com/en-us/dotnet/api/envdte.projectitem.filenames?view=visualstudiosdk-2017)
- Only consider `ProjectItem.Kind=PhysicalFile` for inclusion (package references causing an error)
- Add `LogAndForget` extension method for logging task exceptions to the Visual Studio log

I thought `JoinableTask.FileAndForget` would do this ☝️, but exceptions don't seem to appear in the log. 😕 @AArnott is there a trick to making `FileAndForget` exceptions appear in the log?

Here's the smoking gun.
image

It does appear to be `<PackageReference>` related.

### CODE REVIEW

File: src/VSPackage.cs [hunk 1]
```diff
@@ -92,9 +93,14 @@ private async Task<bool> IsSolutionLoadedAsync()
             return value is bool isSolOpen && isSolOpen;
         }
 
-        private async void HandleOpenSolution(object sender = null, EventArgs e = null)
+        private void HandleOpenSolution(object sender, EventArgs e)
         {
-            await this.JoinableTaskFactory.SwitchToMainThreadAsync();
+            JoinableTaskFactory.RunAsync(HandleOpenSolutionAsync).Task.FileAndForget("StringResourceVisualizer");
```
Comment (davkean) [inline src/VSPackage.cs]: Use JoinableTaskFactory.Run instead of JoinableTaskFactory.RunAsync - it's designed for bridging async -> sync.

**Comment by davkean** [comment]
Not every "ProjectItem" is a file - you should check the ProjectItem.Kind for files, there'll be a constant on VsConstants.

**Comment by jcansdale** [comment]
@davkean,

> Not every "ProjectItem" is a file - you should check the ProjectItem.Kind for files, there'll be a constant on VsConstants.

Thanks for the tip. I've added a filter for `ProjectItem.Kind=PhysicalFile`.

> Use JoinableTaskFactory.Run instead of JoinableTaskFactory.RunAsync - it's designed for bridging async -> sync.

I'm guessing `HandleOpenSolution` was using `async void` was to allow the event to complete asynchronously (maybe @mrlacey will confirm). Although the current implementation seems to do everything on the UI thread, maybe a future implementation could use `VisualStudioWorkspace` and refresh on a background thread. If I understand correctly, `JoinableTaskFactory.Run` would block the calling thread?

**Comment by jcansdale** [comment]
@mrlacey I think this is ready for review. 🤞

**Comment by davkean** [comment]
> JoinableTaskFactory.Run would block the calling thread?

JoinableTaskFactory.Run will block the event handler from continuing until it's done. However, your async version is synchronous executed on the UI anyway - they both block the UI thread for the same amount of time.

**Comment by davkean** [comment]
I think you want to follow the instructions over here: https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#how-to-switch-to-or-use-the-ui-thread-with-a-specific-priority for avoiding blocking the UI thread for too long. For example, try and run this extension in the Roslyn solution http://github.com/dotnet/roslyn and the UI will likely block for a very long time.

**Comment by AArnott** [comment]
@davkean:

> Add LogAndForget extension method for logging task exceptions to the Visual Studio log

The `FileAndForget` method only files telemetry. It doesn't log to the VS activity log. That sounds like a good idea though. I can't remember any reason why we didn't go to the activity log as well. It seems like a great. idea.

File: src/VSPackage.cs [hunk 2]
```diff
@@ -92,9 +93,14 @@ private async Task<bool> IsSolutionLoadedAsync()
...
-        private async void HandleOpenSolution(object sender = null, EventArgs e = null)
+        private void HandleOpenSolution(object sender, EventArgs e)
         {
-            await this.JoinableTaskFactory.SwitchToMainThreadAsync();
+            JoinableTaskFactory.RunAsync(HandleOpenSolutionAsync).Task.LogAndForget(GetType());
+        }
+
+        private async Task HandleOpenSolutionAsync()
+        {
+            await JoinableTaskFactory.SwitchToMainThreadAsync();
```
Comment (AArnott) [inline src/VSPackage.cs]: You should pass a `CancellationToken` to this `SwitchToMainThreadAsync()` call. You'll get one from your `AsyncPackage.InitializeAsync` method, which has one handy.

File: src/VSPackage.cs [hunk 3]
```diff
@@ -74,7 +75,7 @@ protected override async Task InitializeAsync(CancellationToken cancellationToke
 
             if (isSolutionLoaded)
             {
-                HandleOpenSolution();
+                await HandleOpenSolutionAsync();
```
Comment (AArnott) [inline src/VSPackage.cs]: propagate your `cancellationToken` into this async method.

Comment (AArnott) [inline src/VSPackage.cs]: propagate your `cancellationToken` into this async method.

File: src/VSPackage.cs [hunk 4]
```diff
@@ -146,6 +159,7 @@ IEnumerable<ProjectItem> GetProjectFiles(Project proj)
                             // Only want neutral language ones, not locale specific versions
                             if (!System.IO.Path.GetFileNameWithoutExtension(filePath).Contains("."))
                             {
+                                Console.WriteLine(filePath);
```
Comment (AArnott) [inline src/VSPackage.cs]: Can you remove this? VS doesn't generally have a console anyway, but it's tacky to write to the console in a big GUI app.

File: src/VSPackage.cs [hunk 5]
```diff
@@ -189,8 +203,22 @@ IEnumerable<ProjectItem> GetProjectFiles(Project proj)
...
+    {
+        internal static void LogAndForget(this Task task, Type type)
+        {
+            task.ContinueWith(t =>
+            {
+                if (t.Exception != null)
+                {
+                    VsShellUtilities.LogError(type.FullName, t.Exception.ToString());
+                }
+            });
```
Comment (AArnott) [inline src/VSPackage.cs]: Don't call `ContinueWith` without specifying a `TaskScheduler`. In this case, you should be running on the UI thread since you're filing to the activity log and I'm not sure that's a free-thread operation.

Also, you can specify `TaskContinuationOptions.OnlyOnFaulted` and then you can drop your `if` check, and your continuation won't even execute if no error occurs, making it more efficient.

If you also pass `type` in as the `state` parameter to `ContinueWith` and use that state arg in your delegate, you can altogether avoid a closure and delegate allocation with each run of this method, making it *almost* free of runtime cost.

Consider installing the [VSSDK Analyzers](https://aka.ms/vssdkanalyzers) which will catch issues like this.

File: src/VSPackage.cs (hunk 4 above)
Comment (jcansdale) [reply src/VSPackage.cs]: Oops, this was left over testing detritus. ;-)

**Comment by jcansdale** [comment]
@davkean,

> However, your async version is synchronous executed on the UI anyway - they both block the UI thread for the same amount of time.

I'm wondering if this could be changed to use `VisualStudioWorkspace.CurrentSolution` instead of `DTE.Solution`? I'm not sure, but I think `Workspace` might be thread-safe so we could do this work on a background thread?

```
            VisualStudioWorkspace visualStudioWorkspace = ... // how do we find this?
            foreach (var project in visualStudioWorkspace.CurrentSolution.Projects)
            {
                foreach (var document in project.Documents)
                {
                    var postfix = ".Designer.cs";
                    var filePath = document.FilePath;
                    if (!filePath.EndsWith(postfix))
                    {
                        continue;
                    }

                    var resxFile = filePath.Substring(0, filePath.Length - postfix.Length) + ".resx";
                    if (!File.Exists(resxFile))
                    {
                        continue;
                    }

                    // Do stuff with resxFile
                }
            }
```

**Comment by AArnott** [comment]
@davkean said:

> I think you want to follow the instructions over here: https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#how-to-switch-to-or-use-the-ui-thread-with-a-specific-priority for avoiding blocking the UI thread for too long. 

The default priority from `AsyncPackage.InitializeAsync` is already background priority. And if you are within a `JoinableTaskFactory.RunAsync` delegate, the default priority in VS is also background priority. So the only times you really need to think about priority is if you're *not* in a JTF.RunAsync delegate or you need something *higher* in priority.

File: src/VSPackage.cs [hunk 6]
```diff
@@ -92,9 +93,14 @@ private async Task<bool> IsSolutionLoadedAsync()
             return value is bool isSolOpen && isSolOpen;
         }
 
-        private async void HandleOpenSolution(object sender = null, EventArgs e = null)
+        private void HandleOpenSolution(object sender, EventArgs e)
         {
-            await this.JoinableTaskFactory.SwitchToMainThreadAsync();
+            JoinableTaskFactory.RunAsync(() => HandleOpenSolutionAsync(CancellationToken.None)).Task.LogAndForget("StringResourceVisualizer");
```
Comment (AArnott) [inline src/VSPackage.cs]: Use `this.DisposalToken` here. You should cancel doing what you're doing if VS is shutting down.

**Comment by mrlacey** [comment]
Thanks for all the input above.
For some more background:
- Everything was on the UI thread because the VS SDK Analyzer encouraged that. (I removed that analyzer as it made AppVeyor fall over.)
- Was using `DTE.Solution` as `Solution.ActiveSolution` didn't get me access to all projects. I didn't know about `VisualStudioWorkspace.CurrentSolution`
- I think editor snapshots will also help with perf and working off the UI thread but I haven't got my head around them fully yet.


Thanks again for all this input. Learning so much and realizing how much I didn't know.

File: src/VSPackage.cs (hunk 2 above)
Comment (AArnott) [reply src/VSPackage.cs]: No, the cancellation dialog doesn't come up automatically. 
The advantage of doing this is that if VS is shutting down while you're waiting for the UI thread, you won't hold up the shutdown process, but instead this will throw an `OperationCanceledException`, allowing you to skip the UI thread, exit your method, and ultimately unblock VS exiting more quickly.

**Comment by AArnott** [comment]
> Everything was on the UI thread because the VS SDK Analyzer encouraged that.

And that's good. You're accessing DTE which requires the UI thread. I'm not encouraging that you use a background thread. But if your goal in being async is to avoid UI delays, you have to yield the UI thread to other folks in the middle of your long-running work. That doesn't mean switching to a background thread. That just means yielding (i.e. `await Task.Yield()`) periodically.

> I removed that analyzer as it made AppVeyor fall over.

I'd like to learn more about that. These analyzers do work on AppVeyor and other cloud build systems, generally speaking.

**Comment by jcansdale** [comment]
@AArnott,

> The `FileAndForget` method only files telemetry. It doesn't log to the VS activity log. That sounds like a good idea though. I can't remember any reason why we didn't go to the activity log as well. It seems like a great. idea.

The [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.vstasklibraryhelper.fileandforget?view=visualstudiosdk-2017) for `FileAndForget` does seem to imply errors will be sent to the activity logs. For example they say, "This value is also provided as the source (first argument) to TryLogError(String, String)."

Looking at the decompiled source, it looks like this should work. I wonder why it didn't when I tried it. 😕

**Comment by jcansdale** [comment]
@davkean,

> For example, try and run this extension in the Roslyn solution http://github.com/dotnet/roslyn and the UI will likely block for a very long time.

Yup. 

```
[8444] HandleOpenSolutionAsync took 9.8743658 seconds
```

It would be interesting to compare a `VisualStudioWorkspace` based implementation. 🤔

**Comment by jcansdale** [comment]
Here's a possible implementation that uses `VisualStudioWorkspace` instead of `DTE.Solution`: #11. It appears to take a similar about of time, but I think `VisualStudioWorkspace` might be thread safe so you could use a background thread. I'm sure @davkean would know. 🙂

**Comment by AArnott** [comment]
> Update: tried again with FileAndForget and still nothing appears in the log.

Ya, I can see in the source code that it is trying to. But it disregards any failure (since at that point we have nothing left to try or log to). We'd have to step through it in the debugger to see where the failure was.

**Comment by AArnott** [comment]
> Like this?: ace01f3

Yes, although yielding once per project might still cause UI delays when you encounter large projects. You can yield for every project item (inner loop), or you could increment a local integer on the inner loop and yield every 10th iteration, for example.

>  but I think VisualStudioWorkspace might be thread safe so you could use a background thread.

While using the Roslyn API might be thread-safe, an even better aspect of it in this context is that parts of it are immutable. So you can take a snapshot of the Roslyn solution and then operate on it on a background thread and not have to worry like you do with DTE that while you were off the UI thread that the world was changing. Now, the world might actually be changing, but at least it won't corrupt your loop. You'd still have to reconcile changes that were occurring during your loop, after your loop was done.

Also, even on a threadpool thread, you should yield periodically. It doesn't have to be as often, but should still be every ~250ms or so. Otherwise you contribute to [threadpool starvation](https://github.com/Microsoft/vs-threading/blob/master/doc/threadpool_starvation.md) that can once again cause UI delays.

**Comment by mrlacey** [comment]
Switching to using a file system based approach to finding *.resx files (as per suggestion [here](https://github.com/mrlacey/StringResourceVisualizer/issues/11#issuecomment-440225870)) as this removes all issues relating to project type and solution structure.
